export const BurialMapList = [
  //--------遥控面板start--------
  {
    widget_id: 'click_more_func',
    module: '设备',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '更多功能',
  }, {
    widget_id: 'click_temperature_change',
    module: '功能',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '调节温度',
  }, {
    widget_id: 'click_wind_speed',
    module: '风速选择',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '风速',
  }, {
    widget_id: 'click_refrigeration',
    module: '模式',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '制冷',
  }, {
    widget_id: 'click_fan',
    module: '模式',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '送风',
  }, {
    widget_id: 'click_heating',
    module: '模式',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '制热',
  }, {
    widget_id: 'click_upwind_and_downwind',
    module: '风向选择',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '上下风',
  }, {
    widget_id: 'click_anti_direct_blowing',
    module: '防直吹功能',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '防直吹',
  }, {
    widget_id: 'click_fresh_air',
    module: '新风功能',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '新风',
  },
  , {
    widget_id: 'click_lr_angle',
    module: '左右摆风角度',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '左右摆风角度',
  },
  , {
    widget_id: 'click_ud_angle',
    module: '上下摆风角度',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '上下摆风角度',
  },
  {
    widget_id: 'click_ud_around_wind',
    module: '功能',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '上下环绕风',
  },
  {
    widget_id: 'click_ud_wind_blowing',
    module: '功能',
    page_name: '遥控面板',
    page_path: '',
    page_id: 'page_control',
    widget_name: '上下防直吹',
  },
  //--------遥控面板end--------

  //--------更多功能页start----
  {
    widget_id: 'click_confortable',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '舒适',
  },
  {
    widget_id: 'click_remote_control',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '远程控制',
  },
  {
    widget_id: 'click_care_mode',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '关爱模式',
  },
  {
    widget_id: 'click_eco',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: 'ECO',
  },
  {
    widget_id: 'click_dehumidification',
    module: '模式',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '抽湿',
  },
  {
    widget_id: 'click_intelligent_temperature_control',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '智控温',
  },
  {
    widget_id: 'click_sleeping_mode',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '睡眠',
  },
  {
    widget_id: 'click_electric_auxiliary_heat',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '电辅热',
  },
  {
    widget_id: 'click_intelligent_cleaning',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '智清洁',
  },
  {
    widget_id: 'click_voice_control',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '语音',
  },
  {
    widget_id: 'click_appointment_shutdown',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    page_module: '预约关机弹框',
    widget_name: '预约关机确认',
  },
  {
    widget_id: 'click_appointment_switchon',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    page_module: '预约开机弹框',
    widget_name: '预约开机确认',
  },
  {
    widget_id: 'click_screen_display',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '屏显',
  },
  {
    widget_id: 'click_sound',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '声音',
  },
  {
    widget_id: 'click_about_this_machine',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '更多',
  },
  {
    widget_id: 'click_feedback',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '意见反馈',
  },
  {
    widget_id: 'click_sleep_curve',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '睡眠曲线',
  }, 
  {
    widget_id: 'click_cseco',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '舒省',
  },   
  {
    widget_id: 'click_up_nowind_feel',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '上无风感',
  }, 
  {
    widget_id: 'click_down_nowind_feel',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '下无风感',
  }, 
  {
    widget_id: 'click_no_wind_feel',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '无风感',
  },   
  {
    widget_id: 'click_up_swipe_wind',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '上左右风',
  }, 
  {
    widget_id: 'click_down_swipe_wind',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '上左右风',
  }, 
  {
    widget_id: 'click_softwind',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '柔风感',
  }, 
  {
    widget_id: 'click_auto_prevent_cold_wind',
    module: '功能',
    page_name: '更多功能页',
    page_path: '',
    page_id: 'page_more_func',
    widget_name: '智慧防冷风',
  },
  //----------更多功能end-------------

  //----------更多start-----------
  {
    widget_id: 'click_function_description',
    module: '功能',
    page_name: '更多页',
    page_path: '',
    page_id: 'page_about_this_machine',
    widget_name: '功能说明',
  },
  //----------更多end-------------

  //----------远程控制start-----------
  {
    widget_id: 'click_confirm',
    module: '配网',
    page_name: '远程控制-输入WiFi信息页',
    page_path: '',
    page_id: 'page_remote_control_WiFi_info',
    widget_name: '确定',
  },
  {
    widget_id: 'click_retry',
    module: '配网',
    page_name: '远程控制-配网失败页',
    page_path: '',
    page_id: 'page_remote_control_fail',
    widget_name: '重新联网',
  }
  //----------远程控制end-------------
]