#事业部鸿蒙npm插件包配置信息(如下配置示例)
#rm -rf "./src/modules/module_plugin/T0x13"
#  echo "文件夹【module_plugin/T0x13】删除成功！"
rm -rf "./src/modules/module_plugin/T0xBX"
echo "文件夹【module_plugin/T0xBX】删除成功！"
rm -rf "./src/modules/module_plugin/T0xCF"
echo "文件夹【module_plugin/T0xCF】删除成功！"
rm -rf "./src/modules/module_plugin/T0xAC"
echo "文件夹【module_plugin/T0xAC】删除成功！"
rm -rf "./src/modules/module_plugin/T0xFA"
echo "文件夹【module_plugin/T0xFA】删除成功！"
