import { api } from '../../../api'
const tracks = {
  path: 'pages/index/index',
  commonParams: {
    page_id: 'page_home',
    page_name: '小程序首页',
    // module: 'appliance',
    // page_title: '首页'
  },
  elementTracks: [],
  methodTracks: [
    {
      method: 'goAddDevice',
      dataKeys: ['pageText.add_appliance'],
      widget_id: 'click_btn_add_appliance',
      module: 'appliance',
      widget_name: '首页添加设备',
    },
    // {
    // method: 'goAddDeviceJia',
    // dataKeys: ['pageText.tab_add_appliance'],
    // widget_id: 'click_btn_tab_add_appliance',
    // module: 'appliance',
    // widget_name: 'tab+号添加设备',
    // },
    {
      method: 'devicesListDialog',
      dataKeys: ['pageText.popups_home_found'],
      widget_id: '',
      module: 'appliance',
      widget_name: '',
      page_name: '首页自发现弹窗',
      page_id: 'popups_home_found',
    },
    {
      method: 'goNetwork',
      dataKeys: ['pageText.click_found_appliance'],
      widget_id: 'click_found_appliance',
      module: 'appliance',
      widget_name: '设备icon',
    },
    {
      method: 'trackTab',
      dataKeys: ['pageText.switch_tab'],
      page_id: 'page_bottom_tab',
      widget_id: 'switch_tab',
      module: '公共',
      widget_name: '底部tab切换',
      object_type: 'tab',
      object_id: '1',
      object_name: '设备',
    },
    //首页加载相关的埋点
    {
      method: 'getOpendId2Start',
      api_name: api.getOpendId2.api,
      node_desc: '获取openid接口发起请求',
      module: '首页',
    },
    {
      method: 'getOpendId2End',
      api_name: api.getOpendId2.api,
      node_desc: '获取openid接口返回',
      module: '首页',
    },
    {
      method: 'loginMucStart',
      api_name: api.loginMuc.api,
      node_desc: '登录接口发起请求',
      module: '首页',
    },
    {
      method: 'loginMucEnd',
      api_name: api.loginMuc.api,
      node_desc: '登录接口接口返回',
      module: '首页',
    },
    {
      method: 'getIotDeviceImgStart',
      api_name: api.getIotDeviceImg.api,
      node_desc: 'dcp图片接口发起请求',
      module: '首页',
    },
    {
      method: 'getIotDeviceImgEnd',
      api_name: api.getIotDeviceImg.api,
      node_desc: 'dcp图片接口接口返回',
      module: '首页',
    },
    {
      method: 'homeListStart',
      api_name: api.homeList.api,
      node_desc: '家庭列表发起请求',
      module: '首页',
    },
    {
      method: 'homeListEnd',
      api_name: api.homeList.api,
      node_desc: '家庭列表接口返回',
      module: '首页',
    },
    {
      method: 'getIotDeviceV3Start',
      api_name: api.getIotDeviceV3.api,
      node_desc: '新的获取图片接口发起请求',
      module: '首页',
    },
    {
      method: 'getIotDeviceV3End',
      api_name: api.getIotDeviceV3.api,
      node_desc: '新的获取图片接口返回',
      module: '首页',
    },
    {
      method: 'deviceFilterListStart',
      api_name: api.deviceFilterList.api,
      node_desc: '获取当前用户下的设备发起请求',
      module: '首页',
    },
    {
      method: 'deviceFilterListEnd',
      api_name: api.deviceFilterList.api,
      node_desc: '获取当前用户下的设备接口返回',
      module: '首页',
    },
    {
      method: 'applianceListAggregateStart',
      api_name: api.applianceListAggregate.api,
      node_desc: '新首页列表页接口发起请求',
      module: '首页',
    },
    {
      method: 'applianceListAggregateEnd',
      api_name: api.applianceListAggregate.api,
      node_desc: '新首页列表页接口返回',
      module: '首页',
    },
    {
      method: 'getAdvertisement_TokenStart',
      api_name: api.getAdvertisement_Token.api,
      node_desc: '首页广告接口发起请求带token',
      module: '首页',
    },
    {
      method: 'getAdvertisement_TokenEnd',
      api_name: api.getAdvertisement_Token.api,
      node_desc: '首页广告接口返回带token',
      module: '首页',
    },
    {
      method: 'getAdvertisementStart',
      api_name: api.getAdvertisement.api,
      node_desc: '首页广告接口发起请求不带token',
      module: '首页',
    },
    {
      method: 'getAdvertisementEnd',
      api_name: api.getAdvertisement.api,
      node_desc: '首页广告接口返回不带token',
      module: '首页',
    },
    {
      method: 'checkAgreementApiStart',
      api_name: api.checkAgreementApi.api,
      node_desc: '首页校验用户协议是否有更新发起请求',
      module: '首页',
    },
    {
      method: 'checkAgreementApiEnd',
      api_name: api.checkAgreementApi.api,
      node_desc: '首页校验用户协议是否有更新接口返回',
      module: '首页',
    },
    {
      method: 'scanCodeJoinFamilyStart',
      api_name: api.scanCodeJoinFamily.api,
      node_desc: '微信扫一扫美居生成的二维码加入家庭发起请求',
      module: '首页',
    },
    {
      method: 'scanCodeJoinFamilyEnd',
      api_name: api.scanCodeJoinFamily.api,
      node_desc: '微信扫一扫美居生成的二维码加入家庭接口返回',
      module: '首页',
    },
    {
      method: 'nfcBindGetStart',
      api_name: api.nfcBindGet.api,
      node_desc: 'nfc入口才会调用-获取设备绑定信息发起请求',
      module: '首页',
    },
    {
      method: 'nfcBindGetEnd',
      api_name: api.nfcBindGet.api,
      node_desc: 'nfc入口才会调用-获取设备绑定信息接口返回',
      module: '首页',
    },
    {
      method: 'horseHide',
      node_desc: '小木马消失',
      module: '首页',
    },
    {
      method: 'pageOnshow',
      node_desc: '页面onShow触发',
      module: '首页',
    },
    {
      method: 'pageOnLoad',
      node_desc: '页面onLoad触发',
      module: '首页',
    },
    {
      method: 'appOnShow',
      node_desc: 'app.js onShow触发',
      module: '首页',
    },
    //加载相关的埋点结束
    {
      method: 'nfc_NB',
      page_name: 'NFC 读取成功',
      page_id: 'NFC_read_success',
      widget_id: 'jump_to_NB',
      module: 'appliance',
      widget_name: '跳转NB配网',
      object_type: '',
      object_id: '',
      object_name: '',
    },
    //点击非智能设备
    {
      method: 'noSmartDevice',
      module: '非智设备卡片',
      page_name: '小程序首页',
      page_module: '不支持小程序控制的设备',
      page_id: 'page_home',
      widget_id: 'click_no_smart_appliance',
      widget_name: '非智设备卡片',
    },
  ],
}

export default tracks
