var uijson = {
  type: 'page',
  platform: 'mobile1x',
  body: [
    {
      type: 'Image',
      styles: { alpha: 1, placeHolder: 'default_device_icon' },
      layouts: { position: 'absolute', width: '48px', height: '48px', top: '10px', left: '12px' },
      id: 'deviceIcon',
    },
    {
      type: 'Checkbox',
      styles: {
        selected: false,
        iconWidth: '20px',
        iconHeight: '20px',
        normalIcon: 'home_ic_power_off',
        selectedIcon: 'home_ic_power_off',
        normalBgIcon: 'home_bg_power_off',
        selectedBgIcon: 'home_bg_power_on',
        alpha: 1,
      },
      layouts: { position: 'absolute', width: '30px', height: '30px', top: '14px', right: '14px' },
      id: 'powerBtn',
      actions: {
        request: {
          actionType: 'tls.propertys',
          url: '/v1/thing/properties/',
          type: '0',
          method: 'put',
          params: {},
          requestKey: 'wallAirConditioner.power',
        },
      },
    },
    {
      type: 'Text',
      styles: {
        text: '挂式空调',
        fontSize: 13,
        bold: true,
        textColor: '#000000',
        alpha: 1,
        numberOfLines: 1,
        textAlignment: 0,
        lineBreakMode: 2,
      },
      layouts: { position: 'absolute', top: '66px', left: '14px', right: '14px' },
      id: 'deviceName',
    },
    {
      wrapperBody: false,
      type: 'container',
      body: [
        {
          wrapperBody: false,
          type: 'container',
          body: [
            {
              type: 'Text',
              styles: {
                text: '客厅',
                fontSize: 11,
                bold: false,
                textColor: '#999999',
                numberOfLines: 1,
                textAlignment: 0,
                alpha: 1,
              },
              layouts: { position: 'relative', isFixedHeight: false, isFlex: 0, 'flex-grow': 0 },
              id: 'roomName',
            },
          ],
          layouts: {
            display: 'flex',
            position: 'relative',
            'flex-grow': 0,
            'flex-shrink': 0,
            'flex-direction': 'column',
            'justify-content': 'flex-start',
            'flex-wrap': 'nowrap',
            'max-width': '55px',
            overflow: 'hidden',
            'white-space': 'nowrap',
            'text-overflow': 'ellipsis',
            isFixedWidth: false,
            isFlex: 0,
          },
          id: 'roomNameContainer',
        },
        {
          type: 'View',
          styles: { backgroundColor: '#C7C7CC', alpha: 1 },
          layouts: {
            position: 'relative',
            width: '1px',
            height: '10px',
            isFixedHeight: true,
            top: '4px',
            'margin-left': '4px',
            'margin-right': '4px',
          },
          id: 'roomLine',
        },
        {
          wrapperBody: false,
          type: 'container',
          body: [
            {
              type: 'Text',
              styles: {
                text: '速冷中',
                fontSize: 11,
                bold: false,
                textColor: '#999999',
                numberOfLines: 1,
                textAlignment: 0,
                alpha: 1,
              },
              layouts: { position: 'relative', isFixedHeight: false },
              id: 'deviceStatus',
            },
          ],
          layouts: {
            display: 'flex',
            position: 'relative',
            'flex-grow': 1,
            'flex-shrink': 1,
            'flex-basis': '',
            'flex-direction': 'column',
            'justify-content': 'flex-start',
            'flex-wrap': 'nowrap',
            isFixedWidth: false,
            isFlex: 1,
          },
          id: 'id_c715b3a7d276',
        },
      ],
      layouts: {
        display: 'flex',
        position: 'absolute',
        'flex-grow': 1,
        'flex-shrink': 1,
        'flex-basis': '',
        'flex-direction': 'row',
        'justify-content': 'flex-start',
        'flex-wrap': 'nowrap',
        isFixedWidth: true,
        isFlex: 1,
        top: '86px',
        left: '14px',
        right: '14px',
      },
      id: 'id_4edfb9fd5398',
      styles: { alpha: 1 },
    },
  ],
  id: 'id_e12fd4e4c8b9',
  propertyCodes: [
    'wallAirConditioner.power',
    'wallAirConditioner.workMode',
    'wallAirConditioner.targetTemperature',
    'wallAirConditioner.autoWindSpeed',
    'wallAirConditioner.windSpeed',
  ],
  appver: '8.23',
  cardId: 'app_1x1_washingDrive',
}

module.exports = {
  uijson,
}
